# Generated by Django 5.2.6 on 2026-02-22 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
    ]
