# Generated by Django 5.2.11 on 2026-02-24 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0005_branch_alter_subject_options_alter_subject_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Download',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
